<a href="https://colab.research.google.com/github/osunkentangb-create/valentine-app/blob/main/Correct_and_Complete_ANN_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Read your CSV file into a DataFrame
df = pd.read_csv('/content/normal_fault_dataset.csv')

print("Original DataFrame from CSV:")
display(df.head())

Original DataFrame from CSV:


,IA_RMS,IA_DC,IA_MS,TARGET
0,0.647805,-0.000167,0.419652,0
1,2.551790,0.022283,6.511630,1
2,3.058044,0.001151,9.351635,0
3,4.395102,0.002570,19.316926,0
4,4.465588,-0.053434,19.941473,1


To shuffle the data in a pandas DataFrame, you can use the `.sample()` method with `frac=1` (which means sample 100% of the data, effectively shuffling it). You can also add `random_state` for reproducibility.

In [ ]:
# Shuffle the DataFrame
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print("Shuffled DataFrame:")
display(df)

Shuffled DataFrame:


,IA_RMS,IA_DC,IA_MS,TARGET
0,2.653056,0.056611,7.038705,1
1,4.470877,-0.000689,19.988738,0
2,0.614344,0.001893,0.377422,0
3,5.393315,0.367218,29.087842,1
4,3.049203,0.081885,9.297636,1
...,...,...,...,...
355,0.621963,0.001850,0.386842,0
356,8.988069,0.002139,80.785396,0
357,0.615268,0.000818,0.378555,0
358,4.291924,0.037377,18.420608,1


In [ ]:
# Save the shuffled DataFrame to a new CSV file
df.to_csv('shuffled_data.csv', index=False)

print("Shuffled data saved to 'shuffled_data.csv'")

Shuffled data saved to 'shuffled_data.csv'


After executing the above cell, you can download `shuffled_data.csv` from the Colab file browser by clicking on the folder icon on the left sidebar, navigating to the file, and then clicking on the three dots next to the filename to select 'Download'.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Load dataset
data = pd.read_csv('/content/shuffled_data.csv')

print("Dataset shape:", data.shape)
print(data.head())

# Separate features and label
X = data.iloc[:, 0:3].values     # First 3 columns = features
y = data.iloc[:, 3].values       # Last column = label

print("X shape:", X.shape)
print("y shape:", y.shape)

# Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

print("Feature Min:", scaler.data_min_)
print("Feature Max:", scaler.data_max_)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# Build ANN
model = keras.Sequential([
    layers.Dense(9, activation='sigmoid', input_shape=(3,)),
    layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train
model.fit(X_train, y_train, epochs=300, verbose=1)

# Evaluate
loss, acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", acc)

# Extract first layer weights
W1, b1 = model.layers[0].get_weights()

print("\nW1 shape:", W1.shape)
print("b1 shape:", b1.shape)

print("\nW1:\n", W1)
print("\nb1:\n", b1)

Dataset shape: (360, 4)
     IA_RMS     IA_DC      IA_MS  TARGET
0  2.653056  0.056611   7.038705       1
1  4.470877 -0.000689  19.988738       0
2  0.614344  0.001893   0.377422       0
3  5.393315  0.367218  29.087842       1
4  3.049203  0.081885   9.297636       1
X shape: (360, 3)
y shape: (360,)
Feature Min: [ 0.587662 -0.053434  0.345354]
Feature Max: [ 9.235654  0.93794  85.297315]
Epoch 1/300


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.4992 - loss: 0.7253 
Epoch 2/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5015 - loss: 0.7202 
Epoch 3/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5242 - loss: 0.7075 
Epoch 4/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4938 - loss: 0.7145 
Epoch 5/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4695 - loss: 0.7193 
Epoch 6/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4902 - loss: 0.7103 
Epoch 7/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5378 - loss: 0.6972 
Epoch 8/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5318 - loss: 0.6962 
Epoch 9/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5176 - loss: 0.6990 
Epoch 10/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5319 - loss: 0.6954 
Epoch 11/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5311 - loss: 0.6958 
Epoch 12/300
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5087 - loss: 0.6979 


In [ ]:
sample = X_test[0].reshape(1,-1)
prediction = model.predict(sample)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[0.27761853]]


In [ ]:
print(scaler.data_min_)
print(scaler.data_max_)

[ 0.587662 -0.053434  0.345354]
[ 9.235654  0.93794  85.297315]


In [ ]:
import numpy as np

# ==============================
# 1. Generate sine wave (Amplitude = 1)
# ==============================

N = 133                      # number of samples
fs = 8000                   # sampling frequency
f = 60                      # signal frequency

t = np.arange(N) / fs
signal = np.sin(2 * np.pi * f * t)   # sine wave (amplitude = 1)

# ==============================
# 2. Extract Features
# ==============================

dc = np.mean(signal)                # DC component (mean value)
mean_square = np.mean(signal**2)    # Mean Square
rms = np.sqrt(mean_square)          # RMS

print("------ RAW FEATURES ------")
print("DC :", dc)
print("Mean Square :", mean_square)
print("RMS :", rms)

# ==============================
# 3. Scale Features
# ==============================

sample = np.array([[rms, mean_square, dc]])

sample_scaled = scaler.transform(sample)

print("\n------ SCALED FEATURES ------")
print(sample_scaled)

# ==============================
# 4. Predict
# ==============================

prediction = model.predict(sample_scaled)

print("\n------ PREDICTION ------")
print("Output probability:", prediction[0][0])

if prediction[0][0] > 0.5:
    print("Predicted Class: 1 (Fault)")
else:
    print("Predicted Class: 0 (Normal)")

------ RAW FEATURES ------
DC : 7.873018212751119e-05
Mean Square : 0.5012510716129
RMS : 0.70799086972425

------ SCALED FEATURES ------
[[ 0.01391408  0.55951142 -0.00406436]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step

------ PREDICTION ------
Output probability: 0.86989796
Predicted Class: 1 (Fault)


In [ ]:
import numpy as np

# PARAMETERS (same as LabVIEW)
fs = 8000
f = 60
N = 133
t = np.arange(N) / fs

print("Amplitude | RMS | DC | MS | Probability | Class")
print("------------------------------------------------")

for A in np.arange(0, 20, 1):

    # Generate sine signal
    x = A * np.sin(2 * np.pi * f * t)

    # Extract features
    rms = np.sqrt(np.mean(x**2))
    dc = np.mean(x)
    mean_square = np.mean(x**2)

    features = np.array([[rms, dc, mean_square]])

    # Scale features
    features_scaled = scaler.transform(features)

    # Predict
    prob = model.predict(features_scaled, verbose=0)[0][0]
    pred_class = 1 if prob > 0.5 else 0

    print(f"{A:9.2f} | {rms:4.2f} | {dc: .5f} | {mean_square:6.2f} | {prob:11.4f} | {pred_class}")

Amplitude | RMS | DC | MS | Probability | Class
------------------------------------------------
     0.00 | 0.00 |  0.00000 |   0.00 |      0.2428 | 0
     1.00 | 0.71 |  0.00008 |   0.50 |      0.2839 | 0
     2.00 | 1.42 |  0.00016 |   2.01 |      0.3251 | 0
     3.00 | 2.12 |  0.00024 |   4.51 |      0.3646 | 0
     4.00 | 2.83 |  0.00031 |   8.02 |      0.4008 | 0
     5.00 | 3.54 |  0.00039 |  12.53 |      0.4327 | 0
     6.00 | 4.25 |  0.00047 |  18.05 |      0.4594 | 0
     7.00 | 4.96 |  0.00055 |  24.56 |      0.4804 | 0
     8.00 | 5.66 |  0.00063 |  32.08 |      0.4954 | 0
     9.00 | 6.37 |  0.00071 |  40.60 |      0.5043 | 1
    10.00 | 7.08 |  0.00079 |  50.13 |      0.5069 | 1
    11.00 | 7.79 |  0.00087 |  60.65 |      0.5033 | 1
    12.00 | 8.50 |  0.00094 |  72.18 |      0.4936 | 0
    13.00 | 9.20 |  0.00102 |  84.71 |      0.4778 | 0
    14.00 | 9.91 |  0.00110 |  98.25 |      0.4565 | 0
    15.00 | 10.62 |  0.00118 | 112.78 |      0.4301 | 0
    16.00 | 11.33 |  0

In [ ]:
import numpy as np

def debug_WX(A):
    # Signal parameters
    fs = 8000
    f = 60
    N = 133
    t = np.arange(N) / fs
    signal = A * np.sin(1 * np.pi * f * t)

    # Extract features
    rms = np.sqrt(np.mean(x**2))
    dc = np.mean(x)
    mean_square = np.mean(x**2)

    features = np.array([[rms, dc, mean_square]])

    # Scale using trained scaler
    features_scaled = scaler.transform(features)

    # W·X ONLY (no bias)
    WX = np.dot(features_scaled, W1)

    print("\nAmplitude:", A)
    print("Scaled features:", features_scaled)
    print("W·X:", WX)

# Run debug
debug_WX(1)
debug_WX(2)


Amplitude: 1
Scaled features: [[-0.06561741  0.07074154 -0.00406048]]
W·X: [[ 0.10363964  0.03820817 -0.11699715 -0.06618139 -0.10943657  0.09771805
   0.177041    0.04388794  0.12400623]]

Amplitude: 2
Scaled features: [[-0.06561741  0.07074154 -0.00406048]]
W·X: [[ 0.10363964  0.03820817 -0.11699715 -0.06618139 -0.10943657  0.09771805
   0.177041    0.04388794  0.12400623]]


In [ ]:
import numpy as np

def check_scaled_features(A):
    # Signal parameters
    fs = 8000
    f = 60
    N = 133
    t = np.arange(N) / fs
    signal = A * np.sin(2 * np.pi * f * t)

    # Compute our features
    rms = np.sqrt(np.mean(signal**2))
    dc = np.mean(signal)
    ms = np.mean(signal**2)

    print("\nAmplitude:", A)
    print("RAW FEATURES")
    print("RMS :", rms)
    print("DC  :", dc)
    print("MS  :", ms)

    # Put into array
    features = np.array([[rms, dc, ms]])

    # Scale using trained scaler
    features_scaled = scaler.transform(features)

    print("\nSCALED FEATURES")
    print("Scaled RMS :", features_scaled[0,0])
    print("Scaled DC  :", features_scaled[0,1])
    print("Scaled MS  :", features_scaled[0,2])

# Test
check_scaled_features(1)
check_scaled_features(5)
check_scaled_features(10)


Amplitude: 1
RAW FEATURES
RMS : 0.70799086972425
DC  : 7.873018212751119e-05
MS  : 0.5012510716129

SCALED FEATURES
Scaled RMS : 0.013914081988541369
Scaled DC  : 0.05397834740685908
Scaled MS  : 0.0018351203406934882

Amplitude: 5
RAW FEATURES
RMS : 3.53995434862125
DC  : 0.0003936509106379299
MS  : 12.531276790322497

SCALED FEATURES
Scaled RMS : 0.34138472244438356
Scaled DC  : 0.05429600827804434
Scaled MS  : 0.14344486750956223

Amplitude: 10
RAW FEATURES
RMS : 7.0799086972425
DC  : 0.0007873018212758598
MS  : 50.12510716128999

SCALED FEATURES
Scaled RMS : 0.7507230230141864
Scaled DC  : 0.05469308436702582
Scaled MS  : 0.5859753274122771


In [ ]:
print("RMS min:", scaler.data_min_[0])
print("RMS max:", scaler.data_max_[0])

print("DC  min:", scaler.data_min_[1])
print("DC  max:", scaler.data_max_[1])

print("MS  min:", scaler.data_min_[2])
print("MS  max:", scaler.data_max_[2])

RMS min: 0.587662
RMS max: 9.235654
DC  min: -0.053434
DC  max: 0.93794
MS  min: 0.345354
MS  max: 85.297315


In [ ]:
import numpy as np

x = np.array([[0.0247399,0.02474,0.000612071]])

z = np.dot(x, W1) + b1
a1 = 1/(1+np.exp(-z))

print("Z1 =", z)
print("A1 =", a1)

Z1 = [[-0.44035818 -0.38554713  0.36054615  0.31065862  0.55035666 -0.58687483
  -0.59941747 -0.1932818  -0.36159153]]
A1 = [[0.39165562 0.4047897  0.58917263 0.57704602 0.63421834 0.35735223
  0.35447698 0.45182942 0.41057436]]


In [ ]:
W2, b2 = model.layers[1].get_weights()

print("W2 =", W2)
print("b2 =", b2)

W2 = [[ 0.9316257 ]
 [ 0.7265532 ]
 [-1.4897051 ]
 [-1.3216958 ]
 [-1.4508965 ]
 [ 1.3063756 ]
 [ 0.8621632 ]
 [ 0.13302949]
 [ 0.933245  ]]
b2 = [-0.37171292]


In [ ]:
Z2 = np.dot(a1, W2) + b2
print("Z2 =", Z2)

Z2 = [[-1.0575668]]


In [ ]:
A2 = 1 / (1 + np.exp(-Z2))
print("A2 =", A2)

A2 = [[0.25777472]]


TEST ANN

In [ ]:
import numpy as np

def test_signal(A, fs=8000, f=60, N=133):
    """
    Generate a sine signal with amplitude A, extract features, scale,
    and do a forward pass through the trained model.
    """

    # 1️⃣ Generate signal
    t = np.arange(N) / fs
    signal = A * np.sin(2 * np.pi * f * t)

    # 2️⃣ Extract features: RMS, DC, MS
    rms = np.sqrt(np.mean(signal**2))
    dc  = np.mean(signal)
    ms  = np.mean(signal**2)

    features = np.array([[rms, dc, ms]])

    print("\nAmplitude:", A)
    print("RAW FEATURES -> RMS: {:.5f}, DC: {:.5f}, MS: {:.5f}".format(rms, dc, ms))

    # 3️⃣ Scale features
    features_scaled = scaler.transform(features)
    print("SCALED FEATURES ->", features_scaled)

    # 4️⃣ Forward pass through model manually
    W1, b1 = model.layers[0].get_weights()
    W2, b2 = model.layers[1].get_weights()

    # Layer 1
    Z1 = np.dot(features_scaled, W1) + b1
    A1 = 1 / (1 + np.exp(-Z1))  # sigmoid activation
    print("Layer 1 -> Z1:", Z1, "A1:", A1)

    # Layer 2 (output)
    Z2 = np.dot(A1, W2) + b2
    A2 = 1 / (1 + np.exp(-Z2))  # sigmoid output
    print("Output -> Z2:", Z2, "A2 (probability):", A2)

    # 5️⃣ Classification
    pred_class = 1 if A2 > 0.5 else 0
    print("Predicted class:", pred_class)
    return A2, pred_class

# Example tests
test_signal(1)
test_signal(5)
test_signal(10)


Amplitude: 1
RAW FEATURES -> RMS: 0.70799, DC: 0.00008, MS: 0.50125
SCALED FEATURES -> [[0.01391408 0.05397835 0.00183512]]
Layer 1 -> Z1: [[-0.38154011 -0.3491767   0.30488966  0.26185825  0.48414032 -0.51971323
  -0.50607336 -0.16940964 -0.29726849]] A1: [[0.40575549 0.41358208 0.5756374  0.56509304 0.61872507 0.37291929
  0.37611447 0.45774859 0.42622536]]
Output -> Z2: [[-0.9252169]] A2 (probability): [[0.28389611]]
Predicted class: 0

Amplitude: 5
RAW FEATURES -> RMS: 3.53995, DC: 0.00039, MS: 12.53128
SCALED FEATURES -> [[0.34138472 0.05429601 0.14344487]]
Layer 1 -> Z1: [[-0.12569215 -0.05077019  0.20668889 -0.1974881   0.1582368  -0.05083075
  -0.2413248  -0.1332141  -0.14646557]] A1: [[0.46861827 0.48731018 0.55148905 0.45078782 0.53947686 0.48729505
  0.4399599  0.46674564 0.46344893]]
Output -> Z2: [[-0.27065489]] A2 (probability): [[0.43274633]]
Predicted class: 0

Amplitude: 10
RAW FEATURES -> RMS: 7.07991, DC: 0.00079, MS: 50.12511
SCALED FEATURES -> [[0.75072302 0.05469

(array([[0.50687383]]), 1)

In [ ]:
import numpy as np

# PARAMETERS
fs = 8000
f = 60
N = 133
t = np.arange(N) / fs

A = 15 # Amplitude to test

# Generate sine wave
x = A * np.sin(2 * np.pi * f * t)

# Extract features
rms = np.sqrt(np.mean(x**2))
std = np.std(x)
var = np.var(x)

features = np.array([[rms, std, var]])

# Scale features
features_scaled = scaler.transform(features)

# Predict
prob = model.predict(features_scaled, verbose=0)[0][0]
pred_class = 1 if prob > 0.5 else 0

print(f"Amplitude: {A:.2f}")
print(f"Predicted Probability: {prob:.4f}")
print(f"Predicted Class: {pred_class}")

Amplitude: 15.00
Predicted Probability: 0.4508
Predicted Class: 0
